### ISSUE TITLE
Publish files to NPM

### ISSUE THREAD

**Issue by blakepettersson** [relmify/jest-fp-ts#1]
**Describe the issue**
Hello,

It seems like there aren't any files when adding `jest-fp-ts` as a dependency :(
Looking into my `node_modules` there's only a `package.json` referring to thebrodmann/jest-fp-ts
It might be the case that I'm doing something wrong, but at this point I'm not sure of what...

**To Reproduce**

```
yarn add --dev jest-fp-ts
```

```ts
# In jest.setup.ts
import 'jest-fp-ts';
```

Running any test will then fail with 

`Cannot find module 'jest-fp-ts' from 'jest.setup.ts'`

**Expected behavior**
Being able to use the `jest-fp-ts` matchers

**Suggested fix**
I presume (hope) it's a matter of publishing the files

**Comment by leilapearson** [comment]
Hi @blakepettersson. Good to hear from you and thanks for the issue report :-)

I didn't expect anyone to find this project so soon and without any kind of mention in some sort of forum to be honest, so I thought I'd use it a bit more in my local projects before putting it out on npm - but given your interest I'm happy to go ahead and publish this now rather than later.

**Comment by leilapearson** [comment]
The package has now been published on npm as `@relmify/jest-fp-ts`. Please give it a try @blakepettersson and let me know how it goes.

**Comment by leilapearson** [comment]
Didn't hear back, so I'm going to go ahead and close this issue. Thanks again for the report an the interest.

**Comment by blakepettersson** [comment]
Sorry for the delayed response, this works like a charm! 🎉

**Comment by leilapearson** [comment]
That's great news! Thanks for the update!
