### ISSUE TITLE
These matchers

### ISSUE THREAD

**Issue by waynevanson** [relmify/jest-fp-ts#4]
Great work, this library works as **expect**ed (lol)

I'm using `these` and would love to see matchers for both.

Will you accept a PR?

**Comment by leilapearson** [comment]
@waynevanson I was waiting for someone to make this request! 🥇 

I started on `these` matchers some time ago but since I wasn't using them decided to move onto other things until they were requested. I was actually just thinking to go in and pick up that work again since I noticed the library is getting more and more traction over time. It certainly makes sense to add them to the library.

Though the matchers themselves are simple, the code needs restructuring since all `*Left` and `*Right` matchers will be common to both `either` and `these`.  

Also note that since jest is calling the matchers from its own Javascript code, there's no Typescript type checking when the matchers are called, so no way enforce that certain matchers are only called on certain types.

Anyway, as mentioned I'm partway through the work already - though it has been sitting a while. If I pick this up again and get it done sometime this month would that work for you?

**Comment by waynevanson** [comment]
> Also note that since jest is calling the matchers from its own Javascript code, there's no Typescript type checking when the matchers are called, so no way enforce that certain matchers are only called on certain types.

Good catch.

> If I pick this up again and get it done sometime this month would that work for you?

There's no rush, it's open source!

I'm actually building quickcheck over [here](https://github.com/waynevanson/fp-ts-test), which can be used with and without the matchers. I'll be sure to use this lib in examples!

**Comment by leilapearson** [comment]
Nice!

**Comment by leilapearson** [comment]
Working on this as part of a new major release of the package, which includes improving error messages for all matchers, and properly treating the type of received values as `unknown`.

**Comment by leilapearson** [comment]
Released version 2.0.0 today with These matchers and other changes.
